In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [18]:
#빈 리스트 생성
records=[]

#시작 페이지 지정
page_num = 1

#class 이름이 띄어쓰기로 되어있으면 중첩 class 임.. 둘다 적용한다는 뜻
#dataframe으로 만들기 위해 리스트 안에 리스트 만드는 절차
while True:
    response = requests.get("https://www.ikea.com/kr/ko/search/?query=desk&pageNumber=" + str(page_num))
    
    soup = BeautifulSoup(response.text, 'html.parser')
    
    if len(soup.select('.prodName')) > 0:
        product_names = soup.select('.prodName')
        product_prices = soup.select('.prodPrice')
        product_urls = soup.select('.prodImg')
        page_num += 1
   
        index = 0
        for name in product_names:
            record = []
            record.append(product_names[index].text)
            record.append(product_prices[index].text.strip())
            record.append("https://www.ikea.com" + product_urls[index].get('src'))
            records.append(record)
            index +=1
               
    else:
        break

df = pd.DataFrame(data=records, columns = ["이름", "가격", "이미지 주소"])

df.head()

,이름,가격,이미지 주소
0,MICKE 미케,"₩ 99,900 /개",https://www.ikea.com/kr/ko/images/products/mic...
1,BRÄDA 브레다,"₩ 4,900 /개",https://www.ikea.com/kr/ko/images/products/bra...
2,VITTSJÖ 빗셰,"₩ 29,900 /개",https://www.ikea.com/kr/ko/images/products/vit...
3,MICKE 미케,"₩ 59,900 /개",https://www.ikea.com/kr/ko/images/products/mic...
4,ISBERGET 이스베리에트,"₩ 2,500 /개",https://www.ikea.com/kr/ko/images/products/isb...

In [41]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# 코드를 작성하세요.
response = requests.get("https://workey.codeit.kr/ratings/index")
soup = BeautifulSoup(response.text, 'html.parser')
weeks = soup.select('#weekSelectBox option')[0].text
rank = soup.select('.row .rank')[1:]
channel = soup.select('.row .channel')[1:]
program = soup.select('.row .program')[1:]
percent = soup.select('.row .percent')[1:]
records =[]
for i in range(0, len(rank)):
    record = []
    record.append(weeks)
    record.append(rank[i].text)
    record.append(channel[i].text)
    record.append(program[i].text)
    record.append(percent[i].text)
    records.append(record)

columns = []
df = pd.DataFrame(data=records, columns=['period', 'rank', 'channel', 'program', 'rating'])
# 결과 출력
df

                    period rank channel         program rating
0  2009.12.28 ~ 2010.01.03    1    KBS2   주말연속극(수상한삼형제)   33.4
1  2009.12.28 ~ 2010.01.03    2    KBS1   일일연속극(다함께차차차)   33.1
2  2009.12.28 ~ 2010.01.03    3    KBS2           해피선데이   27.1
3  2009.12.28 ~ 2010.01.03    4     MBC       MBC연기대상2부   24.4
4  2009.12.28 ~ 2010.01.03    5     SBS    주말극장(천만번사랑해)   24.2
5  2009.12.28 ~ 2010.01.03    6     MBC     MBC방송연예대상2부   24.0
6  2009.12.28 ~ 2010.01.03    7     MBC     MBC방송연예대상1부   22.4
7  2009.12.28 ~ 2010.01.03    8     SBS       SBS연예대상2부   21.1
8  2009.12.28 ~ 2010.01.03    9     MBC  주말기획드라마(보석비빔밥)   20.9
9  2009.12.28 ~ 2010.01.03   10     MBC  일일시트콤(지붕뚫고하이킥)   19.9

In [42]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# 기간 지정
years = list(range(2010, 2019))
months = list(range(1, 13))
weeks = list(range(0, 5))

# 페이지를 담는 빈 리스트 생성
rating_pages = []

for year in years:
    for month in months:
        for week in weeks:
            # HTML 코드 받아오기
            response = requests.get("https://workey.codeit.kr/ratings/index?year=" + str(year) + "&month=" + str(month) + "&weekIndex=" + str(week))

            # BeautifulSoup 타입으로 변환하기
            soup = BeautifulSoup(response.text, 'html.parser')

            # "row" 클래스가 1개를 넘는 경우만 페이지를 리스트에 추가
            if len(soup.select('.row')) > 1:
                rating_pages.append(soup)

# 레코드를 담는 빈 리스트 만들기
records = []

# 각 페이지 파싱해서 정보 얻기
for page in rating_pages:
    date = page.select('option[selected=selected]')[2].text
    ranks = page.select('.row .rank')[1:]
    channels = page.select('.row .channel')[1:]
    programs = page.select('.row .program')[1:]
    percents = page.select('.row .percent')[1:]

    # 페이지에 있는 10개의 레코드를 리스트에 추가
    for i in range(10):
        record = []
        record.append(date)
        record.append(ranks[i].text)
        record.append(channels[i].text)
        record.append(programs[i].text)
        record.append(percents[i].text)
        records.append(record)

# DataFrame 만들기
df = pd.DataFrame(data=records, columns=['period', 'rank', 'channel', 'program', 'rating'])

# 결과 출력
df.head()

                    period rank channel        program rating
0  2009.12.28 ~ 2010.01.03    1    KBS2  주말연속극(수상한삼형제)   33.4
1  2009.12.28 ~ 2010.01.03    2    KBS1  일일연속극(다함께차차차)   33.1
2  2009.12.28 ~ 2010.01.03    3    KBS2          해피선데이   27.1
3  2009.12.28 ~ 2010.01.03    4     MBC      MBC연기대상2부   24.4
4  2009.12.28 ~ 2010.01.03    5     SBS   주말극장(천만번사랑해)   24.2